import { demoResponse } from "./demoData";

// Always dynamic — SSE and other streaming responses must never be cached or
// statically generated by Next.js.
export const dynamic = "force-dynamic";

const API_PROXY_TARGET = (process.env.API_PROXY_TARGET || "http://api:8000").replace(/\/+$/, "");
const DEMO_MODE = process.env.UI_DEMO_DATA === "true" || process.env.NEXT_PUBLIC_DEMO_DATA === "true";
const DEMO_FALLBACK =
  process.env.NODE_ENV !== "production" && process.env.UI_DEMO_FALLBACK !== "false";

function buildUpstreamUrl(path: string[] | undefined, requestUrl: string): string {
  const normalizedPath = Array.isArray(path) ? path.join("/") : "";
  const incoming = new URL(requestUrl);
  const suffix = incoming.search || "";
  return `${API_PROXY_TARGET}/${normalizedPath}${suffix}`;
}

function copyRequestHeaders(headers: Headers): Headers {
  const nextHeaders = new Headers(headers);
  nextHeaders.delete("host");
  nextHeaders.delete("connection");
  nextHeaders.delete("content-length");
  return nextHeaders;
}

function copyResponseHeaders(headers: Headers): Headers {
  const nextHeaders = new Headers(headers);
  // Keep transfer-encoding so chunked SSE responses are forwarded correctly.
  // Remove only headers that cause problems when re-sent by the proxy layer.
  nextHeaders.delete("content-encoding");
  nextHeaders.delete("connection");
  return nextHeaders;
}

function isStreamingResponse(headers: Headers): boolean {
  const ct = headers.get("content-type") || "";
  return ct.includes("text/event-stream");
}

async function proxy(request: Request, path: string[] | undefined): Promise<Response> {
  const demoRequest = request.clone();
  const explicitDemoResponse = DEMO_MODE ? await demoResponse(request.clone(), path) : null;
  if (explicitDemoResponse) {
    return explicitDemoResponse;
  }
  const upstreamUrl = buildUpstreamUrl(path, request.url);
  const method = request.method.toUpperCase();
  const init: RequestInit = {
    method,
    headers: copyRequestHeaders(request.headers),
    redirect: "manual",
  };
  if (method !== "GET" && method !== "HEAD") {
    init.body = await request.text();
  }
  // Use a longer timeout for header receipt (not body); SSE bodies stay open indefinitely.
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 120_000);
  init.signal = controller.signal;
  try {
    const upstream = await fetch(upstreamUrl, init);
    clearTimeout(timeoutId);
    const responseHeaders = copyResponseHeaders(upstream.headers);
    // For SSE / streaming responses, pipe through a new ReadableStream so each
    // chunk reaches the browser immediately instead of being buffered by the
    // Next.js response layer.
    if (isStreamingResponse(upstream.headers) && upstream.body) {
      const upstreamBody = upstream.body;
      const passThrough = new ReadableStream({
        async start(controller) {
          const reader = upstreamBody.getReader();
          try {
            for (;;) {
              const { done, value } = await reader.read();
              if (done) { controller.close(); break; }
              controller.enqueue(value);
            }
          } catch (e) {
            controller.error(e);
          }
        },
      });
      return new Response(passThrough, {
        status: upstream.status,
        statusText: upstream.statusText,
        headers: responseHeaders,
      });
    }
    return new Response(upstream.body, {
      status: upstream.status,
      statusText: upstream.statusText,
      headers: responseHeaders,
    });
  } catch (error) {
    clearTimeout(timeoutId);
    const fallbackResponse = DEMO_FALLBACK ? await demoResponse(demoRequest, path) : null;
    if (fallbackResponse) {
      return fallbackResponse;
    }
    const isTimeout =
      (error instanceof Error && error.name === "AbortError") ||
      (error instanceof Error && (error as NodeJS.ErrnoException).code === "UND_ERR_HEADERS_TIMEOUT");
    if (isTimeout) {
      return new Response(JSON.stringify({ detail: "Upstream timeout" }), {
        status: 503,
        headers: { "content-type": "application/json" },
      });
    }
    return new Response(JSON.stringify({ detail: "Upstream unavailable" }), {
      status: 502,
      headers: { "content-type": "application/json" },
    });
  }
}

type RouteContext = {
  params: Promise<{ path: string[] }>;
};

export async function GET(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}

export async function POST(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}

export async function PUT(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}

export async function PATCH(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}

export async function DELETE(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}

export async function OPTIONS(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}

export async function HEAD(
  request: Request,
  context: RouteContext
): Promise<Response> {
  const { path } = await context.params;
  return proxy(request, path);
}
